version: '3'
services:
  tech-radar:
    container_name: server
    image: tech-radar-server
    build: .
    command: npm start
    volumes:
      - ./storage:/usr/app/storage
    ports:
      - ${PORT_OUTER}:${PORT_INNER}
    environment:
      - NODE_USER=admin
      - NODE_PASS=change!moi
      - FRONTEND_BRANCH=${FRONTEND_BRANCH}
      - NODE_PORT=${PORT_INNER}
